valores = input().split(' ')
n1 = int(valores[0])
n2 = int(valores[1])
n3 = int(valores[2])
lista = [n1,n2,n3]
crescente = sorted(lista)
a = int(crescente[0])
b = int(crescente[1])
c = int(crescente[2])
print(a)
print(b)
print(c)
print()
print(n1)
print(n2)
print(n3)